name: "Catho node custom action"
description: "Action to start action node jobs"

inputs:
  npm-token:
    description: "NPM Token to create .npmrc file"
    required: false
    default: ""
  working-directory:
    description: "Working directory"
    required: false
    default: ./

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/checkout@v3

    - run: touch .npmrc
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - run: echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" >> ./.npmrc
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      if: ${{ inputs.npm-token != '' }}

    - run: npm install
      shell: bash
      working-directory: ${{ inputs.working-directory }}

